### ISSUE TITLE
how to generate checkpoint.pth file

### ISSUE THREAD

**Issue by saghafi** [3ZadeSSG/TwitterSentimentAnalysisApp#1]
in the GoogleCloudDeployment folder and  TwitterAnalyzer file and getTwitterSentiment function it require to load checkpoint.pth but this file there isn't, do you know how to generate this file?
`model=load_checkpoint('checkpoint.pth',vocab_to_int)`

**Comment by 3ZadeSSG** [comment]
I couldn't upload the model checkpoint file as it was over 300 MB. You will have to run the notebook which is in second folder "Training with preprocessed data"
it will generate the trained model checkpoint file.
